/* 
 * File:   main.c
 * Author: James Paul
 *
 * Created on May 30, 2013, 2:10 PM
 */

#include "uart_setup.h"
#include "prototypes.h"
#include <p24Exxxx.h>
#include "misc.h"
#include "timersetup.h"

// PIC24EP256GP204 Configuration Bit Settings

#include <xc.h>

enum receiver_state{connecting, connected_waiting};
enum receiver_state system_state;

// FICD
#pragma config ICS = PGD3               // ICD Communication Channel Select bits (Communicate on PGEC3 and PGED3)
#pragma config JTAGEN = OFF             // JTAG Enable bit (JTAG is disabled)

// FPOR
#pragma config ALTI2C1 = OFF            // Alternate I2C1 pins (I2C1 mapped to SDA1/SCL1 pins)
#pragma config ALTI2C2 = OFF            // Alternate I2C2 pins (I2C2 mapped to SDA2/SCL2 pins)
#pragma config WDTWIN = WIN25           // Watchdog Window Select bits (WDT Window is 25% of WDT period)

// FWDT
#pragma config WDTPOST = PS32768        // Watchdog Timer Postscaler bits (1:32,768)
#pragma config WDTPRE = PR128           // Watchdog Timer Prescaler bit (1:128)
#pragma config PLLKEN = ON              // PLL Lock Enable bit (Clock switch to PLL source will wait until the PLL lock signal is valid.)
#pragma config WINDIS = OFF             // Watchdog Timer Window Enable bit (Watchdog Timer in Non-Window mode)
#pragma config FWDTEN = OFF              // Watchdog Timer Enable bit (Watchdog timer always enabled)

// FOSC
#pragma config POSCMD = XT              // Primary Oscillator Mode Select bits (XT Crystal Oscillator Mode)
#pragma config OSCIOFNC = OFF           // OSC2 Pin Function bit (OSC2 is clock output)
#pragma config IOL1WAY = ON             // Peripheral pin select configuration (Allow only one reconfiguration)
#pragma config FCKSM = CSDCMD           // Clock Switching Mode bits (Both Clock switching and Fail-safe Clock Monitor are disabled)


// FOSCSEL
#pragma config FNOSC = PRIPLL              // Oscillator Source Selection (Primary Oscillator with PLL module (XT + PLL, HS + PLL, EC + PLL))
#pragma config IESO = ON                // Two-speed Oscillator Start-up Enable bit (Start up device with FRC, then switch to user-selected oscillator source)

// FGS
#pragma config GWRP = OFF               // General Segment Write-Protect bit (General Segment may be written)
#pragma config GCP = OFF                // General Segment Code-Protect bit (General Segment Code protect is Disabled)


// The above was code generated by MPLAB using the Configuration bits window

char data;
char string[32];
int read_index;
int next;

int main(int argc, char** argv) {


    configureOscillator();
    configureINT();
    setupUART2();
    configureUART2pins();
    configureT1();
    setupLEDs();
    configureHorn();
    //timer2setupPWM();


    wait(10000);
//    char send1[]  = "$$$";
//    SerialTransmit(send1);
//    wait(10000);
//    char send2[] = "SR,0006664FAE62\n";
//    SerialTransmit(send2);

    system_state = connecting;

    while(1){
        switch(system_state){
            case connecting:
                while(strcmp(string,"0006664FAE62\r\n" != 0))
                    cautionLights();
                clear_receive_buffer();
                char send3[] = "0006664D63FA\r\n";
                SerialTransmit(send3);
                system_state = connected_waiting;

            case connected_waiting:
                headLightsOn();
        }
    }


    return(0);
}

void _ISR _U2RXInterrupt(void)
{
    // put the received character into a var
    data = U2RXREG;

    // put the char into the read buffer at the right spot
    string[read_index] = data;
    read_index++;

    next = 1;

    // Clear the RX interrupt Flag
    IFS1bits.U2RXIF = 0;
}

void clear_receive_buffer(void) {
    memset(string,0,32);
    read_index = 0;
}
